export const UPDATE_TOTAL_PRICE = 'UPDATE_TOTAL_PRICE';
export const GET_ORDER_DETAILS = 'GET_ORDER_DETAILS';
export const GET_ORDER_DETAILS_SUCCESS = 'GET_ORDER_DETAILS_SUCCESS';
export const GET_ORDER_DETAILS_FAILED = 'GET_ORDER_DETAILS_FAILED';
export const OPEN_POPUP_ORDER = 'OPEN_POPUP_ORDER';
export const DELETE_ORDER_NUMBER = 'DELETE_ORDER_NUMBER';
export const CLOSE_POPUP_ORDER = 'CLOSE_POPUP_ORDER';