export const GET_INGREDIENTS = 'GET_INGREDIENTS';
export const GET_INGREDIENTS_SUCCESS = 'GET_INGREDIENTS_SUCCESS';
export const GET_INGREDIENTS_FAILED = 'GET_INGREDIENTS_FAILED';
export const GET_INGREDIENT_INFORMATION = 'GET_INGREDIENT_INFORMATION';
export const DELETE_INGREDIENT_INFORMATION = 'DELETE_INGREDIENT_INFORMATION';
export const OPEN_POPUP = 'OPEN_POPUP';
export const DELETE_VIEWED_iNGREDIENT = 'DELETE_VIEWED_iNGREDIENT';
export const CLOSE_POPUP = 'CLOSE_POPUP';